/**
 * Generated Ghostty Configuration Schema
 *
 * Generated on: 2025-11-22T14:28:19.295Z
 *
 * DO NOT EDIT THIS FILE MANUALLY - it is generated by scripts/generateSchema.ts
 */

import type { GhosttySchema, ConfigProperty } from '@/types/schema';

export const GHOSTTY_SCHEMA: GhosttySchema = {
  version: '1.0.0',
  categories: [
    {
      id: 'appearance',
      displayName: 'Appearance',
      icon: 'Palette',
      sections: [
        {
          id: 'background',
          displayName: 'Background',
          properties: [
            {
              key: 'background-opacity',
              displayName: 'Background Opacity',
              type: 'number',
              category: 'appearance',
              section: 'background',
              description:
                'The opacity of the terminal background. 1.0 is fully opaque, 0.0 is fully transparent.',
              defaultValue: '1.0',
              isRepeatable: false,
              validation: {
                min: 0,
                max: 1,
              },
              examples: ['background-opacity = 0.95'],
            },
            {
              key: 'background-blur-radius',
              displayName: 'Background Blur Radius',
              type: 'number',
              category: 'appearance',
              section: 'background',
              description:
                'The blur radius for the background when using transparency. Only works on supported platforms.',
              defaultValue: '0',
              isRepeatable: false,
              validation: {
                min: 0,
                max: 100,
              },
              examples: ['background-blur-radius = 20'],
            },
          ],
        },
        {
          id: 'cursor',
          displayName: 'Cursor',
          properties: [
            {
              key: 'cursor-style',
              displayName: 'Cursor Style',
              type: 'enum',
              category: 'appearance',
              section: 'cursor',
              description: 'The style of the cursor.',
              defaultValue: 'block',
              isRepeatable: false,
              validation: {
                enum: ['block', 'bar', 'underline'],
              },
              examples: ['cursor-style = bar'],
            },
            {
              key: 'cursor-blink',
              displayName: 'Cursor Blink',
              type: 'boolean',
              category: 'appearance',
              section: 'cursor',
              description: 'Whether the cursor should blink.',
              defaultValue: 'false',
              isRepeatable: false,
              examples: ['cursor-blink = true'],
            },
          ],
        },
        {
          id: 'font',
          displayName: 'Font',
          properties: [
            {
              key: 'font-family',
              displayName: 'Font Family',
              type: 'string',
              category: 'appearance',
              section: 'font',
              description:
                'The font family to use for the terminal. This can be a single font family name or a comma-separated list of font families.',
              defaultValue: 'monospace',
              isRepeatable: false,
              examples: ['font-family = JetBrains Mono'],
            },
            {
              key: 'font-size',
              displayName: 'Font Size',
              type: 'number',
              category: 'appearance',
              section: 'font',
              description: 'The font size in points.',
              defaultValue: '12',
              isRepeatable: false,
              validation: {
                min: 6,
                max: 72,
              },
              examples: ['font-size = 14'],
            },
          ],
        },
        {
          id: 'theme',
          displayName: 'Theme',
          properties: [
            {
              key: 'theme',
              displayName: 'Theme',
              type: 'enum',
              category: 'appearance',
              section: 'theme',
              description: 'The color theme to use. Ghostty comes with several built-in themes.',
              defaultValue: 'default',
              isRepeatable: false,
              validation: {
                enum: [
                  'default',
                  'nord',
                  'dracula',
                  'solarized-dark',
                  'solarized-light',
                  'monokai',
                  'gruvbox-dark',
                  'gruvbox-light',
                ],
              },
              examples: ['theme = nord'],
            },
            {
              key: 'palette',
              displayName: 'Palette',
              type: 'repeatable',
              category: 'appearance',
              section: 'theme',
              description:
                'Define a color palette entry. This property can be specified multiple times. Format: palette = index=#hexcolor',
              defaultValue: '(ANSI standard colors)',
              isRepeatable: true,
              examples: ['palette = 0=#1d1f21'],
            },
          ],
        },
      ],
    },
    {
      id: 'config',
      displayName: 'Config',
      icon: 'FileText',
      sections: [
        {
          id: 'config',
          displayName: 'Config',
          properties: [
            {
              key: 'config-file',
              displayName: 'Config File',
              type: 'repeatable',
              category: 'config',
              section: 'config',
              description:
                'Include another config file. This property can be specified multiple times.',
              defaultValue: null,
              isRepeatable: true,
              examples: ['config-file = ~/.config/ghostty/theme.conf'],
            },
          ],
        },
      ],
    },
    {
      id: 'input',
      displayName: 'Input',
      icon: 'Keyboard',
      sections: [
        {
          id: 'keybinds',
          displayName: 'Keybinds',
          properties: [
            {
              key: 'keybind',
              displayName: 'Keybind',
              type: 'repeatable',
              category: 'input',
              section: 'keybinds',
              description:
                'Define a keybinding. This property can be specified multiple times. Format: keybind = key>action',
              defaultValue: null,
              isRepeatable: true,
              examples: ['keybind = ctrl+shift+c>copy_to_clipboard'],
            },
            {
              key: 'mouse-scroll-multiplier',
              displayName: 'Mouse Scroll Multiplier',
              type: 'number',
              category: 'input',
              section: 'keybinds',
              description: 'Multiplier for mouse scroll speed.',
              defaultValue: '1.0',
              isRepeatable: false,
              validation: {
                min: 0.1,
                max: 10,
              },
              examples: ['mouse-scroll-multiplier = 1.5'],
            },
          ],
        },
      ],
    },
    {
      id: 'notifications',
      displayName: 'Notifications',
      icon: 'Bell',
      sections: [
        {
          id: 'bell',
          displayName: 'Bell',
          properties: [
            {
              key: 'bell-action',
              displayName: 'Bell Action',
              type: 'enum',
              category: 'notifications',
              section: 'bell',
              description: 'Action to take when the bell character is received.',
              defaultValue: 'visual',
              isRepeatable: false,
              validation: {
                enum: ['none', 'visual', 'sound', 'system'],
              },
              examples: ['bell-action = system'],
            },
          ],
        },
        {
          id: 'notifications',
          displayName: 'Notifications',
          properties: [
            {
              key: 'desktop-notifications',
              displayName: 'Desktop Notifications',
              type: 'boolean',
              category: 'notifications',
              section: 'notifications',
              description: 'Enable desktop notifications for terminal bell.',
              defaultValue: 'true',
              isRepeatable: false,
              examples: ['desktop-notifications = false'],
            },
          ],
        },
      ],
    },
    {
      id: 'platform',
      displayName: 'Platform',
      icon: 'Monitor',
      sections: [
        {
          id: 'gtk',
          displayName: 'Gtk',
          properties: [
            {
              key: 'gtk-titlebar',
              displayName: 'Gtk Titlebar',
              type: 'boolean',
              category: 'platform',
              section: 'gtk',
              description: 'Use GTK titlebar on Linux with GTK.',
              defaultValue: 'true',
              isRepeatable: false,
              examples: ['gtk-titlebar = false'],
              platform: 'Linux (GTK)',
            },
          ],
        },
        {
          id: 'linux',
          displayName: 'Linux',
          properties: [
            {
              key: 'linux-csd',
              displayName: 'Linux Csd',
              type: 'boolean',
              category: 'platform',
              section: 'linux',
              description: 'Enable client-side decorations on Linux.',
              defaultValue: 'true',
              isRepeatable: false,
              examples: ['linux-csd = false'],
              platform: 'Linux',
            },
          ],
        },
        {
          id: 'macos',
          displayName: 'Macos',
          properties: [
            {
              key: 'macos-titlebar-style',
              displayName: 'Macos Titlebar Style',
              type: 'enum',
              category: 'platform',
              section: 'macos',
              description: 'The style of the titlebar on macOS.',
              defaultValue: 'native',
              isRepeatable: false,
              validation: {
                enum: ['native', 'transparent', 'hidden'],
              },
              examples: ['macos-titlebar-style = transparent'],
              platform: 'macOS',
            },
            {
              key: 'macos-option-as-alt',
              displayName: 'Macos Option As Alt',
              type: 'enum',
              category: 'platform',
              section: 'macos',
              description: 'Treat the Option key as Alt on macOS.',
              defaultValue: 'false',
              isRepeatable: false,
              validation: {
                enum: ['true', 'false', 'left', 'right'],
              },
              examples: ['macos-option-as-alt = true'],
              platform: 'macOS',
            },
          ],
        },
      ],
    },
    {
      id: 'system',
      displayName: 'System',
      icon: 'Settings',
      sections: [
        {
          id: 'auto-update',
          displayName: 'Auto Update',
          properties: [
            {
              key: 'auto-update',
              displayName: 'Auto Update',
              type: 'enum',
              category: 'system',
              section: 'auto-update',
              description: 'Enable automatic updates.',
              defaultValue: 'check',
              isRepeatable: false,
              validation: {
                enum: ['off', 'check', 'download'],
              },
              examples: ['auto-update = download'],
            },
            {
              key: 'working-directory',
              displayName: 'Working Directory',
              type: 'string',
              category: 'system',
              section: 'auto-update',
              description: 'The initial working directory for new shells.',
              defaultValue: '(home directory)',
              isRepeatable: false,
              examples: ['working-directory = /Users/myuser/projects'],
            },
          ],
        },
      ],
    },
    {
      id: 'terminal',
      displayName: 'Terminal',
      icon: 'Terminal',
      sections: [
        {
          id: 'terminal',
          displayName: 'Terminal',
          properties: [
            {
              key: 'shell',
              displayName: 'Shell',
              type: 'string',
              category: 'terminal',
              section: 'terminal',
              description:
                "The shell to use. If not specified, Ghostty will use the user's default shell.",
              defaultValue: null,
              isRepeatable: false,
              examples: ['shell = /bin/zsh'],
            },
            {
              key: 'scrollback-lines',
              displayName: 'Scrollback Lines',
              type: 'number',
              category: 'terminal',
              section: 'terminal',
              description: 'The number of lines to keep in the scrollback buffer.',
              defaultValue: '10000',
              isRepeatable: false,
              validation: {
                min: 0,
                max: 100000,
              },
              examples: ['scrollback-lines = 50000'],
            },
            {
              key: 'mouse-hide-while-typing',
              displayName: 'Mouse Hide While Typing',
              type: 'boolean',
              category: 'terminal',
              section: 'terminal',
              description: 'Hide the mouse cursor while typing.',
              defaultValue: 'true',
              isRepeatable: false,
              examples: ['mouse-hide-while-typing = false'],
            },
            {
              key: 'copy-on-select',
              displayName: 'Copy On Select',
              type: 'boolean',
              category: 'terminal',
              section: 'terminal',
              description: 'Automatically copy selected text to clipboard.',
              defaultValue: 'false',
              isRepeatable: false,
              examples: ['copy-on-select = true'],
            },
          ],
        },
      ],
    },
    {
      id: 'ui',
      displayName: 'Ui',
      icon: 'Layout',
      sections: [],
    },
    {
      id: 'window',
      displayName: 'Window',
      icon: 'RectangleHorizontal',
      sections: [
        {
          id: 'window',
          displayName: 'Window',
          properties: [
            {
              key: 'window-width',
              displayName: 'Window Width',
              type: 'number',
              category: 'window',
              section: 'window',
              description: 'The initial window width in pixels.',
              defaultValue: '800',
              isRepeatable: false,
              validation: {
                min: 400,
                max: 7680,
              },
              examples: ['window-width = 1200'],
            },
            {
              key: 'window-height',
              displayName: 'Window Height',
              type: 'number',
              category: 'window',
              section: 'window',
              description: 'The initial window height in pixels.',
              defaultValue: '600',
              isRepeatable: false,
              validation: {
                min: 300,
                max: 4320,
              },
              examples: ['window-height = 800'],
            },
            {
              key: 'window-padding-x',
              displayName: 'Window Padding X',
              type: 'number',
              category: 'window',
              section: 'window',
              description: 'Horizontal padding inside the window in pixels.',
              defaultValue: '2',
              isRepeatable: false,
              validation: {
                min: 0,
                max: 100,
              },
              examples: ['window-padding-x = 10'],
            },
            {
              key: 'window-padding-y',
              displayName: 'Window Padding Y',
              type: 'number',
              category: 'window',
              section: 'window',
              description: 'Vertical padding inside the window in pixels.',
              defaultValue: '2',
              isRepeatable: false,
              validation: {
                min: 0,
                max: 100,
              },
              examples: ['window-padding-y = 10'],
            },
            {
              key: 'window-title',
              displayName: 'Window Title',
              type: 'string',
              category: 'window',
              section: 'window',
              description: 'The initial window title.',
              defaultValue: 'Ghostty',
              isRepeatable: false,
              examples: ['window-title = My Terminal'],
            },
          ],
        },
      ],
    },
  ],
};

/**
 * Quick lookup map of all properties by key
 */
export const PROPERTY_MAP = new Map<string, ConfigProperty>([
  [
    'background-opacity',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'appearance')!
      .sections.find(s => s.id === 'background')!
      .properties.find(p => p.key === 'background-opacity')!,
  ],
  [
    'background-blur-radius',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'appearance')!
      .sections.find(s => s.id === 'background')!
      .properties.find(p => p.key === 'background-blur-radius')!,
  ],
  [
    'cursor-style',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'appearance')!
      .sections.find(s => s.id === 'cursor')!
      .properties.find(p => p.key === 'cursor-style')!,
  ],
  [
    'cursor-blink',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'appearance')!
      .sections.find(s => s.id === 'cursor')!
      .properties.find(p => p.key === 'cursor-blink')!,
  ],
  [
    'font-family',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'appearance')!
      .sections.find(s => s.id === 'font')!
      .properties.find(p => p.key === 'font-family')!,
  ],
  [
    'font-size',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'appearance')!
      .sections.find(s => s.id === 'font')!
      .properties.find(p => p.key === 'font-size')!,
  ],
  [
    'theme',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'appearance')!
      .sections.find(s => s.id === 'theme')!
      .properties.find(p => p.key === 'theme')!,
  ],
  [
    'palette',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'appearance')!
      .sections.find(s => s.id === 'theme')!
      .properties.find(p => p.key === 'palette')!,
  ],
  [
    'config-file',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'config')!
      .sections.find(s => s.id === 'config')!
      .properties.find(p => p.key === 'config-file')!,
  ],
  [
    'keybind',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'input')!
      .sections.find(s => s.id === 'keybinds')!
      .properties.find(p => p.key === 'keybind')!,
  ],
  [
    'mouse-scroll-multiplier',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'input')!
      .sections.find(s => s.id === 'keybinds')!
      .properties.find(p => p.key === 'mouse-scroll-multiplier')!,
  ],
  [
    'bell-action',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'notifications')!
      .sections.find(s => s.id === 'bell')!
      .properties.find(p => p.key === 'bell-action')!,
  ],
  [
    'desktop-notifications',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'notifications')!
      .sections.find(s => s.id === 'notifications')!
      .properties.find(p => p.key === 'desktop-notifications')!,
  ],
  [
    'gtk-titlebar',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'platform')!
      .sections.find(s => s.id === 'gtk')!
      .properties.find(p => p.key === 'gtk-titlebar')!,
  ],
  [
    'linux-csd',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'platform')!
      .sections.find(s => s.id === 'linux')!
      .properties.find(p => p.key === 'linux-csd')!,
  ],
  [
    'macos-titlebar-style',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'platform')!
      .sections.find(s => s.id === 'macos')!
      .properties.find(p => p.key === 'macos-titlebar-style')!,
  ],
  [
    'macos-option-as-alt',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'platform')!
      .sections.find(s => s.id === 'macos')!
      .properties.find(p => p.key === 'macos-option-as-alt')!,
  ],
  [
    'auto-update',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'system')!
      .sections.find(s => s.id === 'auto-update')!
      .properties.find(p => p.key === 'auto-update')!,
  ],
  [
    'working-directory',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'system')!
      .sections.find(s => s.id === 'auto-update')!
      .properties.find(p => p.key === 'working-directory')!,
  ],
  [
    'shell',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'terminal')!
      .sections.find(s => s.id === 'terminal')!
      .properties.find(p => p.key === 'shell')!,
  ],
  [
    'scrollback-lines',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'terminal')!
      .sections.find(s => s.id === 'terminal')!
      .properties.find(p => p.key === 'scrollback-lines')!,
  ],
  [
    'mouse-hide-while-typing',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'terminal')!
      .sections.find(s => s.id === 'terminal')!
      .properties.find(p => p.key === 'mouse-hide-while-typing')!,
  ],
  [
    'copy-on-select',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'terminal')!
      .sections.find(s => s.id === 'terminal')!
      .properties.find(p => p.key === 'copy-on-select')!,
  ],
  [
    'window-width',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'window')!
      .sections.find(s => s.id === 'window')!
      .properties.find(p => p.key === 'window-width')!,
  ],
  [
    'window-height',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'window')!
      .sections.find(s => s.id === 'window')!
      .properties.find(p => p.key === 'window-height')!,
  ],
  [
    'window-padding-x',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'window')!
      .sections.find(s => s.id === 'window')!
      .properties.find(p => p.key === 'window-padding-x')!,
  ],
  [
    'window-padding-y',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'window')!
      .sections.find(s => s.id === 'window')!
      .properties.find(p => p.key === 'window-padding-y')!,
  ],
  [
    'window-title',
    GHOSTTY_SCHEMA.categories
      .find(c => c.id === 'window')!
      .sections.find(s => s.id === 'window')!
      .properties.find(p => p.key === 'window-title')!,
  ],
]);
